#!/bin/bash
#setup.sh
clear
#color
blue='\e[1;31m'
green='\e[0;25m'
purple='\e[1;36m'
white='\e[1;37m'
red='\e[1;30m'


echo -e $white "Instalasi Script!!"
sleep 4
echo -e $green "Tunggu...😀"
Sleep 5
clear
apt update && apt upgrade -y
clear
pkg install python && pkg install python2 -y
clear
apt install git
clear
chmod +x *


clear
sleep 3
